export default function Terms(){
const term=[
    {title:'1. USE OF THE SITE',Dis:'PLEASE CAREFULLY REVIEW THE TERMS OF USE OF THIS SITE AND THE TERMS OF OUR PRIVACY STATEMENT BEFORE USING THIS SITE OR ANY OF OUR SITES, OR ANY GOODS OR SERVICES FROM OUR SITE. By using this Site, including downloading or accessing Materials, ordering products or otherwise using the Services, you agree to be bound by, and acknowledge your acceptance of these Terms of Use. From time to time, we may update these Terms of Use. We encourage you to periodically review these terms for any material changes. You agree to be bound by all of the provisions of these Terms of Use that are displayed on the Site on the date you use the Site and/or any part of the Service. Your use of the Site, and/or any part of the Service, indicates your acceptance of all of the provisions of these Terms of Use that are displayed on the Site on the date of such use.'},
    {title:'2. DESCRIPTION OF SITE AND THE SERVICE.',Dis:'We may provide, through the Site, services (defined herein as “Services”) that include without limitation the: (a) provision of the Site and other online services and Internet sites; (b) display, performance, provision, and use of: information such as educational, promotional, product, pricing, marketing or other valuable information ("Information"); copyrighted works, photographs, text, music, video, sound, graphics, messages, and other Materials, including Our Materials and Third Party Materials ("Content"); and our and Third Parties Trademarks; (c) interactive communication through chat, message boards, VOIP and other media, and (d) offering of products and services for sale, license, distribution or use.You can contact us about this Site or about accessing and changing any personal information you provide at this Site through contact information contained on the Site.'},
    {title:'3.OWNERSHIP OF INTELLECTUAL PROPERTY OF THIS SITE AND MATERIALS.',Dis:' Trademarks, Copyright and Intellectual Property Ownership. We use names, marks, brands, design marks, slogans, logos, designs, trade dress and trade names on the Site or with the Service ("Our Trademarks”). We own all Trademarks, the Content (subject to a Third Party owning its Intellectual Property) , and other information displayed and posted on, contained in, and/or provided in connection with, the Site and/or the Service (collectively, "Our Materials”). Also, third parties have allowed us to post or use their materials and Trademarks on the Site ("Third Party Materials"). We refer to Our Materials and Third Party Materials collectively as the Materials.'},
    {title:'3.1 Copyright Notice.',Dis:'Our Materials contained on the Site are copyrighted materials of Campus Crusade for Christ, Inc. Copyright © 1993-2021 Campus Crusade for Christ, Inc. All rights reserved. International copyright secured. We exclusively own, or have the right to use or license, all intellectual property in the Materials, proprietary information and know-how used with the Site and Services. We maintain all of the web pages of the Site as a collective work under the U.S. copyright laws and protect the Site and Materials under others  trademark and other intellectual property laws.'},
    {title:'3.2 Rights in Materials',Dis:'By using or accessing the Site or Services, you do not acquire any rights or interest in any Materials. The only rights you can gain are those we explicitly grant to you through these Terms of Use. We reserve all rights that we do not expressly grant to you.You agree not to display, use (including co-branding your owns goods or services with our Trademark), remove, or alter Our Organization’s or Third Party Trademarks, Content or other Information without prior written consent. You also agree that any use by you, or on your behalf, of our Trademarks, and the goodwill associated therewith, shall insure to our benefit.'},
    {title:'4. GENERAL USE RULES.',Dis:'By using or accessing the Site or Services, you agree to adhere to the following General Use Rules. We reserve the right to suspend or terminate your access to the Site, and to refuse any and all current or future access to, or use of, the Site and the Service for violation of any of the following General Use Rules.  (a) You agree not to use obscene, racist, vulgar, discourteous, indecent or sexually explicit language or images. You agree not to post, upload, e-mail, transmit, distribute, or otherwise make available, any such content or materials onto any of the Site, including any Forum (defined below)   (b) You agree not to post or communicate infringing material or harassing communications or advertisements. You also agree not to post, communicate, upload, e-mail, transmit, distribute, or otherwise make available: any material or content that infringes and/or violates any right of a third party (including its intellectual property and proprietary rights), or any law;  any harassing, slanderous, libelous or derogatory information or content, or any advertisements for products or services, "junk mail", spam, chain mail, pyramid schemes, or other form of commercial or illegal solicitation  (c) You agree not to use the Forum or the Site for commercial purposes of any kind; (d) You agree not to harm, or attempt to harm, lure or deceive minors in any way by your use or access of the Site or Services; (e) You agree not to create or use a false identity for the purpose of misleading others; (f) You agree not to collect or store personal data about other users; (g) You agree not to post or distribute any software or other materials that contain a virus, worm, trojan horse or other harmful or disabling code or component;  (h) You agree not to interfere with, or disrupt, the operation of the Site and/or the Service, or with servers or networks connected to, or used in connection with the operation of the Site; (i) You agree not to disobey any requirements, procedures, policies or regulations established by the owners or operators of any networks, hardware, or software connected to, or used in connection with the operation of the Site, or any requirement that we post on the Site; and (j) You agree to respect the privacy of others. You agree not to post or disclose phone numbers, addresses, Social Security numbers, or any other private information, relating to any other person.'},
    {title:'5. LIMITED LICENSE FOR DOWNLOADABLE MATERIALS.',Dis:'We may identify certain materials on our Site as being downloadable ("Licensed Materials"). You may download one copy of these identified downloadable materials subject to the restrictions of the Terms. We grant to you a limited, non-exclusive, non-transferable, non-sublicensable, license to view, print, and make one copy of the Licensed Materials for only informational, educational, non-commercial, personal purposes and without alteration of the materials (the "License"). You can use the Licensed Materials only in the format in which we make them available on the Site for download, and only in authorized distributions   The License is subject to the following additional restrictions:   (a) You cannot charge or collect any Distribution Fee for the distribution of any of the Licensed Materials. The term "Distribution Fee" means any and all payments of monies, fees, royalties, remuneration, donations, gifts or other consideration, whether in cash or like-kind, received by, paid to, owed to, on or behalf of, a user or a distributor that arise from, or are in any way related to the provision, transmission, distribution, sale, license, lease, rental or other use of the Licensed Materials, including specifically without limitation, any fundraising activities;  (b) All copyright, trademark or other proprietary notices that appear on the Licensed Materials, together with the permission notice, must appear on all copies of the Licensed Materials that you make or distribute;   (c) You shall not use, copy or distribute any graphics comprising part of the Licensed Materials separate from accompanying text;  (d) You shall not use the Licensed Materials in connection with, or relation to, any fundraising activities;  (e) You shall not use the Licensed Materials in a manner that suggests an association with or endorsement by us, or any of our products, services, or brands; and  (f) You shall not download quantities of Licensed Materials to a database that can be used to avoid future downloads of any of the Licensed Materials from any of the Sites.'},
{title:'6. Reservation of Rights.',Dis:'We reserve any rights not expressly granted herein.'},
{title:' 7. Termination of License.',Dis:'We may terminate the License and any of the rights at any time by providing notice of termination on the Site or directly to you as a user. Further, the License shall automatically terminate without notice if you breach any of the terms or conditions of the License or these Terms of Use. Upon termination of the License, you agree to immediately destroy, and cease all use or distribution of, any downloaded, printed or electronically stored copies of the Licensed Materials or General Content.'}
,
{title:'8. Ownership in Posted Material.',Dis:'By uploading or communicating any materials, ideas or submissions to any of our Site, including any Forum, or submitting any materials to us in any other manner, you automatically grant (or warrant that the owner of such materials expressly granted) to us a perpetual, royalty-free, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, publicly perform and display, create derivative works from and distribute such materials, or to incorporate such materials into any form, medium, or technology now known or later developed. In addition, you waive and warrant that all so-called "moral rights" in those materials have been waived. You agree that we own any derivative works, improvements or other materials, works, ideas, intellectual property, and/or products created from, based on, or related to, our access to, or use of, any materials you provide. If on a particular Site we have included an upload license, those terms should be noted as also applying, with any conflicts governed by these Terms of Use.'}
,
{title:'9. Disclaimer on Information Received from Volunteers.',Dis:'Our Organization provides general information regarding spiritual matters and religious questions through the Internet and Ministry Response Center Volunteers. We make this information available solely for informational and educational purposes. Please be aware that the information is not prepared by licensed counselors, medical or mental health professionals and it is not provided as medical, mental, or other professional advice. You should not use or rely on any information or advice provided by Our Ministry or any Volunteer in lieu of medical, mental health, physical or other professional assistance or counseling. Instead, you should always consult with your physician, psychologist, psychiatrist, pastor, rabbi, priest, cleric or other spiritual advisor.'}
]
return(
    <div>
 <div>
           
           <h1 className='text-center mt-20'>Terms of Use</h1>
           {term.map((data,index)=>(
               <div className='md:ml-32 md:mr-32 mr-5 ml-5 mt-5'> 
           <h4>{data.title}</h4>
           <p className='text-justify'>{data.Dis}</p>
           </div>
           ))}
                   </div>
    </div>
)
}